# Title

In [6]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [14]:
a = tf.constant([[1,2],[3,4]])
print(f'a dimention: {tf.rank(a)}')

b = tf.Variable(3)
print(f'b dimention: {tf.rank(b)}')

c = tf.constant(np.random.rand(3,2))
print(f'c dimention: {tf.rank(c)}')


d = tf.constant(np.random.rand(3,3,2))
print(f'c dimention: {tf.rank(d)}')

a dimention: 2
b dimention: 0
c dimention: 2
c dimention: 3


In [21]:
x = tf.Variable(2)
x.assign(3)
print(x.numpy())

y = tf.Variable(4)
f = x * x * y * y + 3
print(f.numpy())

a1 = tf.matmul(a, a)
print(a1.numpy())

3
147
[[ 7 10]
 [15 22]]


In [26]:
a2 = a + 6
print(a2.numpy())

a3 = tf.square(a)
print(a3.numpy())

a4 = tf.cast(a, tf.float32)
a5 = tf.sqrt(a4)
print(a5.numpy())

[[ 7  8]
 [ 9 10]]
[[ 1  4]
 [ 9 16]]
[[1.        1.4142135]
 [1.7320508 2.       ]]


### Transform data

In [30]:
a6 = np.sqrt(a4)
print (a6)

s1 = tf.constant("abc")
tf.strings.length(s1).numpy()


[[1.        1.1892071]
 [1.316074  1.4142135]]


3

### Gradient

In [33]:
x = tf.Variable(2.0)
with tf.GradientTape(persistent=False, watch_accessed_variables=True) as tape:
    f = x ** 2
    
gradient = tape.gradient(f, x)
print(gradient)

tf.Tensor(4.0, shape=(), dtype=float32)


In [50]:
x = tf.Variable(4.0)
w = tf.Variable(2.0)
with tf.GradientTape(persistent=True, watch_accessed_variables=False) as tape:
    tape.watch([x, w])
    y = x ** 3 - 2* x + 1
    f = w ** 2 + 2
    
g = tape.gradient(y, x)
print(g)
print(tape.gradient(f,w))

tf.Tensor(46.0, shape=(), dtype=float32)
None
